
import Image from 'next/image'
import MyPic from '../../../../public/Assets/test.jpg'
import Head from 'next/head';


export async function generateMetadata({ params }) {
    // const product = await getProduct(params.id);
    console.log(params.id,'params id')
    console.log(decodeURIComponent(params.id),'params id')
    return { 
        title: params.id ,
        twitter:{
            card:'summary_large_image',
            title:'bayu.js',
            description:'this is your fvckn description',
            siteId:'12971917292',
            creator:'Gorillaworkoutjs',
            creatorId:'asdasdasdasd',
            images:decodeURIComponent(params.id)
          },
          openGraph:{
            title:'open graph js',
            description:'doushite',
            url:'https://gorillaworkout.space',
            siteName:'next.js',
            images:[{
              url:decodeURIComponent(params.id),
              width:400,
              height:400
            }]
          }
    };
  }
// export const metadata = {
//   twitter:{
//     card:'summary_large_image',
//     title:'bayu.js',
//     description:'this is your fvckn description',
//     siteId:'12971917292',
//     creator:'Gorillaworkoutjs',
//     creatorId:'asdasdasdasd',
//     images:['https://domf5oio6qrcr.cloudfront.net/medialibrary/11203/283fb478-5554-44aa-b37f-7917a90f38d7.jpg']
//   },
//   openGraph:{
//     title:'open graph js',
//     description:'doushite',
//     url:'https://gorillaworkout.space',
//     siteName:'next.js',
//     images:[{
//       url:'https://domf5oio6qrcr.cloudfront.net/medialibrary/11203/283fb478-5554-44aa-b37f-7917a90f38d7.jpg',
//       width:400,
//       height:400
//     }]
//   }
//   // title: 'Create Next App',
//   // description: 'Generated by create next app',
// }

// high
export default function Page({params}){
    return (
        <>
            <Head>
                <title>CERTIFICATE {params.id}</title>
                <meta name="description" content="this is from @gorillaworkout." />
                <meta property="og:image" content={MyPic} />
                <meta property="og:image:width" content="1200" />
                <meta property="og:image:height" content="630" />
            </Head>
            <div className="w-screen h-screen flex flex-col justify-center items-center"> 
            <h1>CERTIFICATE {params.id}</h1>
            <h2>{decodeURIComponent(params.id)}</h2>
            {/* <Image
                src={MyPic}
                alt="Image description"
                width={300}
                height={300}
            /> */}
            </div>
        </>
        
    )
}

// export const getServerSideProps =  () => {
//     // const res = await fetch('https://api.github.com/repos/vercel/next.js');
//     // const repo = await res.json();
//     // return { props: { repo } };
//     return {
//         props:{
//             data:'asdasdasd'
//         }
//     }
//   };