import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   twitter:{
//     card:'summary_large_image',
//     title:'bayu.js',
//     description:'this is your fvckn description',
//     siteId:'12971917292',
//     creator:'Gorillaworkoutjs',
//     creatorId:'asdasdasdasd',
//     images:['https://domf5oio6qrcr.cloudfront.net/medialibrary/11203/283fb478-5554-44aa-b37f-7917a90f38d7.jpg']
//   },
//   openGraph:{
//     title:'open graph js',
//     description:'doushite',
//     url:'https://gorillaworkout.space',
//     siteName:'next.js',
//     images:[{
//       url:'https://domf5oio6qrcr.cloudfront.net/medialibrary/11203/283fb478-5554-44aa-b37f-7917a90f38d7.jpg',
//       width:400,
//       height:400
//     }]
//   }
//   // title: 'Create Next App',
//   // description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
