import Image from 'next/image'
import MyPic from '../../../public/Assets/test.jpg'
import Head from 'next/head';

// export const metadata = {

//     twitter:{
//       card:'summary_large_image',
//       title:'bob.js',
//       description:'this is your bob description',
//       siteId:'12971917292',
//       creator:'bobJS',
//       creatorId:'bobobobobo',
//       images:['https://awsimages.detik.net.id/visual/2023/02/06/10-pekerjaan-dengan-gaji-tertinggi-tahun-2023-1_169.jpeg?w=650']
//     },
//     openGraph:{
//       title:'open bob js',
//       description:'doushite',
//       url:'https://gorillaworkout.space',
//       siteName:'next.js',
//       images:[{
//         url:'https://awsimages.detik.net.id/visual/2023/02/06/10-pekerjaan-dengan-gaji-tertinggi-tahun-2023-1_169.jpeg?w=650',
//         width:400,
//         height:400
//       }]
//     }
//     // title: 'Create Next App',
//     // description: 'Generated by create next app',
//   }
export default function Page(){

    return (
        <>
            <Head>
                <title>CERTIFICATE</title>
                <meta name="description" content="this is from @gorillaworkout." />
                <meta property="og:image" content={MyPic} />
                <meta property="og:image:width" content="1200" />
                <meta property="og:image:height" content="630" />
            </Head>
            <div className="w-screen h-screen flex justify-center items-center"> 
                
            <Image
                src={MyPic}
                alt="Image description"
                width={300}
                height={300}
            />
            </div>
        </>
    )
}